# Generated by Django 3.2.22 on 2023-10-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='CarsReport',
        ),
    ]
