# Generated by Django 3.2.22 on 2023-10-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarManager', '0002_rename_car_carsreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsreport',
            name='damage_severity',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
