# Generated by Django 3.2.22 on 2023-10-14 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CarManager', '0003_carsreport_damage_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsreport',
            name='car_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carsreport',
            name='license_plate',
            field=models.CharField(default='', max_length=15),
        ),
    ]
