# Generated by Django 3.2.22 on 2023-10-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarManager', '0005_auto_20231014_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsreport',
            name='car_leave_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
