# Generated by Django 3.2.22 on 2023-10-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarManager', '0006_alter_carsreport_car_leave_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsreport',
            name='license_plate',
            field=models.CharField(default='X', max_length=15, unique=True),
        ),
    ]
